#!/usr/bin/env ruby

require "awp3"

if ARGV[0] == 'max'
 return p Awp3::Grabber.new('Time.now', 'Time.now', 'max').grab_files.size
end

grabs = Awp3::Grabber::new(ARGV[0], ARGV[1], ARGV[2]).grab

if ARGV[3] == 'test'
  p grabs
  print "\n\n----END GRABS---\n\n"
  grabs.each do |grab|
    Awp3::Commit.new(grab[:files], grab[:time]).commit!
  end

  return p 'This was a test nothing was committed!'
end

grabs.each do |grab|
  Awp3::Commit.new(grab[:files], grab[:time]).commit!
end
